import json, datetime
from enum import Enum

CLASSES = {}
DEFAULT_CLASS = {}
ID_CLASS = {}

DATA_TYPES = {
    'NInt': '0',
    'NFloat': '0',
    'NBool': 'False',
    'NString': None,
    'HSVString': '',
    'GroupList': '[]',
    'ParticleString': '',
    'RemapList': 7,
    'AdvRandomList': 8,
    'SequenceList': 9,
    'EventList': 10,
    'GroupID': 11,
    'ColorID': 12,
    'ItemID': 13,
    'TimerID': 14,
    'BlockID': 15,
    'ControlID': 16,
    'EffectID': 17,
    'UniqueID': 18,
    'SFXGroup': 19,
    'ChannelID': 20,
    'ForceID': 21,
    'ColorOrGroupID': 22,
    'GroupOrControlID': 23,
    'GroupOrEffectID': 24,
    'ItemOrTimerID': 25,
    'Easing': 26,
    'XYOnly': 27,
    'Color1P9': 28,
    'SingleColorType': 29,
    'TriggerLayer': 30,
    'SoundDirs': 31,
    'KeyframeRotDir': 32,
    'KeyframeMode': 33,
    'StopMode': 34,
    'AdvancedFollowMode': 35,
    'AdvancedFollowPage2Mode': 36,
    'AreaDirButtonsDir': 37,
    'AreaCenterSpecial': 38,
    'Background': 39,
    'Ground': 40,
    'MiddleGround': 41,
    'TouchPlayerOnly': 42,
    'TouchToggle': 43,
    'InstantCountComparison': 44,
    'GradientBlend': 45,
    'CameraEdge': 46,
    'ReverbType': 47,
    'PickupMultiplyDivide': 48,
    'ItemTriggerTyp': 49,
    'ItemTriggerOp': 50,
    'ItemTriggerAbsNeg': 51,
    'ItemTriggerRounding': 52,
    'ItemTriggerCompareOp': 53,
    'SequenceMode': 54,
    'ArrowDir': 55,
    'LabelAlign': 56,
    'LabelSpecial': 57,
    'UIRef': 58,
    'OptionSet': 59,
    'TeleportGravity': 60,
    'EnterExitOnly': 61,
    'BPMSpeed': 62
}
   

def get_inheritence_string(classes):
    if (len(classes) == 0):
        return ''
    

    str = '('

    for index, item in enumerate(classes):
        str += f'{item}{', ' if (index < len(classes) - 1) else ')'}'


    return str

def get_default(type: str):
    i = DATA_TYPES[type]
    match (type):
        case 'Bool':
            return 'False'
        case "Float" | "Int":
            return "0"
        case "String":
            return "\'\'"
        

        case 0:
            pass

def get_properties_string(props):
    string = ''

    for name, item in props.items():
        type_str = 'None'
        type_case = item[1]
        actual_case = False

        match (item[1]):
            case 'Int':
                type_case = 'NInt'
            case 'Float':
                type_case = 'NFloat'
            case 'Bool':
                type_case = 'NBool'
        
        if (item[1] in ['GroupID', 'ColorID', 'ItemID', 'TimerID', 'BlockID', 'ControlID', 'EffectID', 'UniqueID', 'SFXGroup', 'ChannelID', 'ForceID', 'ColorOrGroupID', 'GroupOrControlID', 'GroupOrEffectID', 'ItemOrTimerID']):
            type_case = 'NInt'
            actual_case = True


        

        string += f'        self.{name} = {type_case}()    {f'#Actual type is {item[1]}()' if actual_case else ''}\n'
    return string


def get_formatted_properties_string(props):
    string = ''

    for name, item in props.items():
        string += f'{' '*8}self._{name} = {item[0]}\n'
    return string


with open('NeditGD/Dictionaries/objs.json', 'r') as f:
    data = json.load(f)

with open('NeditGD/Dictionaries/output.py', 'w') as f:
    f.write('#!-- Autogenerated by ClassGenerator.py at --!#\n')
    f.write(f'#!-- {datetime.datetime.now().astimezone()} --!#\n\n')

    f.write('from NeditGD import Object, HSV\n')
    f.write('from DataTypes import *\n')
    f.write('from enum import Enum\n\n\n')

    f.write('\n\n')
    
    for class_name in data['classes']:
        inherits = []
        properties = {}


        for ihclass_name in data['classes'][class_name]['inherits']:
            inherits.append(ihclass_name)

        for index, field in enumerate(data['classes'][class_name]['fields']):
            properties[field['name']] = (field['id'], field['type'], field['note'])

        
        f.write(f'class {class_name}{get_inheritence_string(inherits) if len(inherits) > 0 else ''}:\n')
        
        f.write(f'    def __init__(self):\n')
        if (class_name == 'Common'): f.write(f'{' '*8}self._object = Object()\n\n')
        if (len(inherits) > 0): f.write(f'{' '*8}super().__init__()\n\n')
        f.write(f'{' '*8}#Property Types:\n{get_properties_string(properties) if len(properties) > 0 else f'{'    '*2}pass\n'}\n')
        f.write(f'{' '*8}#Property IDs:\n{get_formatted_properties_string(properties) if len(properties) > 0 else '\n'}')
        f.write('\n\n')



