#!-- Autogenerated by EnumGenerator.py @ 2026-08-06 20:05:09.533608-05:00 --!#

from enum import Enum

class Easing(Enum):
    NONE = 0
    EASE_IN_OUT = 1
    EASE_IN = 2
    EASE_OUT = 3
    ELASTIC_IN_OUT = 4
    ELASTIC_IN = 5
    ELASTIC_OUT = 6
    BOUNCE_IN_OUT = 7
    BOUNCE_IN = 8
    BOUNCE_OUT = 9
    EXPONENTIAL_IN_OUT = 10
    EXPONENTIAL_IN = 11
    EXPONENTIAL_OUT = 12
    SINE_IN_OUT = 13
    SINE_IN = 14
    SINE_OUT = 15
    BACK_IN_OUT = 16
    BACK_IN = 17
    BACK_OUT = 18


class XYOnly(Enum):
    NEITHER = 0
    X_ONLY = 1
    Y_ONLY = 2


class Color1P9(Enum):
    DEFAULT = 0
    P1 = 1
    P2 = 2
    LBG = 3
    COL1 = 4
    COL2 = 5
    COL3 = 6
    COL4 = 7
    DL3 = 8


class SingleColorType(Enum):
    DEFAULT = 0
    BASE = 1
    DETAIL = 2


class TriggerLayer(Enum):
    BG = 0
    MG = 1
    B5 = 2
    B4 = 3
    B3 = 4
    B2 = 5
    B1 = 6
    P = 7
    T1 = 8
    T2 = 9
    T3 = 10
    T4 = 11
    G = 12
    UI = 13
    MAX = 14


class SoundDirs(Enum):
    ALL = 0
    LEFT_RIGHT = 1
    LEFT = 2
    RIGHT = 3
    UP_DOWN = 4
    DOWN = 5
    UP = 6


class KeyframeRotDir(Enum):
    UNSET = 0
    CW = 1
    CCW = 2


class KeyframeMode(Enum):
    TIME = 0
    EVEN = 1
    DIST = 2


class StopMode(Enum):
    STOP = 0
    PAUSE = 1
    RESUME = 2


class AdvancedFollowMode(Enum):
    INIT = 0
    SET = 1
    ADD = 2


class AdvancedFollowPage2Mode(Enum):
    M0 = 0
    M1 = 1
    M2 = 2


class AreaDirButtonsDir(Enum):
    ALL = 0
    HORIZ = 1
    VERT = 2


class AreaCenterSpecial(Enum):
    P1 = 0
    P2 = 1
    C = 2
    BL = 3
    CL = 4
    TL = 5
    BC = 6
    TC = 7
    BR = 8
    CR = 9
    TR = 10


class Background(Enum):
    BG1 = 0
    BG2 = 1
    BG3 = 2
    BG4 = 3
    BG5 = 4
    BG6 = 5
    BG7 = 6
    BG8 = 7
    BG9 = 8
    BG10 = 9
    BG11 = 10
    BG12 = 11
    BG13 = 12
    BG14 = 13
    BG15 = 14
    BG16 = 15
    BG17 = 16
    BG18 = 17
    BG19 = 18
    BG20 = 19
    BG21 = 20
    BG22 = 21
    BG23 = 22
    BG24 = 23
    BG25 = 24
    BG26 = 25
    BG27 = 26
    BG28 = 27
    BG29 = 28
    BG30 = 29
    BG31 = 30
    BG32 = 31
    BG33 = 32
    BG34 = 33
    BG35 = 34
    BG36 = 35
    BG37 = 36
    BG38 = 37
    BG39 = 38
    BG40 = 39
    BG41 = 40
    BG42 = 41
    BG43 = 42
    BG44 = 43
    BG45 = 44
    BG46 = 45
    BG47 = 46
    BG48 = 47
    BG49 = 48
    BG50 = 49
    BG51 = 50
    BG52 = 51
    BG53 = 52
    BG54 = 53
    BG55 = 54
    BG56 = 55
    BG57 = 56
    BG58 = 57
    BG59 = 58


class Ground(Enum):
    G1 = 0
    G2 = 1
    G3 = 2
    G4 = 3
    G5 = 4
    G6 = 5
    G7 = 6
    G8 = 7
    G9 = 8
    G10 = 9
    G11 = 10
    G12 = 11
    G13 = 12
    G14 = 13
    G15 = 14
    G16 = 15
    G17 = 16
    G18 = 17
    G19 = 18
    G20 = 19
    G21 = 20
    G22 = 21


class MiddleGround(Enum):
    NONE = 0
    MG1 = 1
    MG2 = 2
    MG3 = 3


class TouchPlayerOnly(Enum):
    UNSET = 0
    P1 = 1
    P2 = 2


class TouchToggle(Enum):
    UNSET = 0
    ON = 1
    OFF = 2


class InstantCountComparison(Enum):
    EQUALS = 0
    LARGER = 1
    SMALLER = 2


class GradientBlend(Enum):
    NORMAL = 0
    ADDITIVE = 1
    MULTIPLY = 2
    INVERT = 3


class CameraEdge(Enum):
    UNSET = 0
    LEFT = 1
    RIGHT = 2
    UP = 3
    DOWN = 4


class ReverbType(Enum):
    GENERIC = 0
    PADDED_CELL = 1
    ROOM = 2
    BATHROOM = 3
    LIVING_ROOM = 4
    STONE_ROOM = 5
    AUDITORIUM = 6
    CONCERT_HALL = 7
    CAVE = 8
    ARENA = 9
    HANGAR = 10
    CARPETED_HALLWAY = 11
    HALLWAY = 12
    STONE_CORRIDOR = 13
    ALLEY = 14
    FOREST = 15
    CITY = 16
    MOUNTAINS = 17
    QUARRY = 18
    PLAIN = 19
    PARKING_LOT = 20
    SEWER_PIPE = 21
    UNDERWATER = 22


class PickupMultiplyDivide(Enum):
    UNSET = 0
    MULTIPLY = 1
    DIVIDE = 2


class ItemTriggerTyp(Enum):
    UNSET = 0
    ITEM = 1
    TIMER = 2
    POINTS = 3
    TIME = 4
    ATT = 5


class ItemTriggerOp(Enum):
    EQ = 0
    ADD = 1
    SUB = 2
    MULT = 3
    DIV = 4


class ItemTriggerAbsNeg(Enum):
    NONE = 0
    ABS = 1
    NEG = 2


class ItemTriggerRounding(Enum):
    NONE = 0
    ROUND = 1
    FLOOR = 2
    CEIL = 3


class ItemTriggerCompareOp(Enum):
    EQ = 0
    GT = 1
    GTE = 2
    LT = 3
    LTE = 4


class SequenceMode(Enum):
    STOP = 0
    LOOP = 1
    LAST = 2


class ArrowDir(Enum):
    UP = 0
    DOWN = 1
    LEFT = 2
    RIGHT = 3


class LabelAlign(Enum):
    UNSET = 0
    LEFT = 1
    RIGHT = 2


class LabelSpecial(Enum):
    UNSET = 0
    MAIN_TIME = 1
    POINTS = 2
    ATTEMPTS = 3


class UIRef(Enum):
    DEFAULT = 0
    AUTO_X = 1
    CENTER_X = 2
    LEFT = 3
    RIGHT = 4
    AUTO_Y = 5
    CENTER_Y = 6
    BOTTOM = 7
    TOP = 8


class OptionSet(Enum):
    UNSET = 0
    ON = 1
    OFF = 2


class TeleportGravity(Enum):
    UNSET = 0
    NORMAL = 1
    FLIPPED = 2
    TOGGLE = 3


class EnterExitOnly(Enum):
    UNSET = 0
    ENTER = 1
    EXIT = 2


class BPMSpeed(Enum):
    NORMAL = 0
    YELLOW = 1
    GREEN = 2
    PINK = 3
    RED = 4


class ColorIDs(Enum):
    BG = 1000
    G1 = 1001
    LINE = 1002
    _3DL = 1003
    OBJ = 1004
    P1 = 1005
    P2 = 1006
    G2 = 1009
    MG = 1013
    MG2 = 1014


