#Same thing as ClassGenerator but for Enums
JSON_PATH = 'NeditGD/Dictionaries/objs.json'
OUTPUT_PATH = 'NeditGD/Dictionaries/Enums.py'

import json, datetime

SINGLE_TAB = ' '*4
DOUBLE_TAB = ' '*8

with open(JSON_PATH, 'r') as f: data = json.load(f)

with open(OUTPUT_PATH, 'w') as f:
    f.write(f'#!-- Autogenerated by EnumGenerator.py @ {datetime.datetime.now().astimezone()} --!#\n\n')

    f.write('from enum import Enum\n\n')
    for type_name in data['types']:
        type_data = data['types'][type_name]

        if type_data['type'] != 'enum': continue
        f.write(f"class {type_name}(Enum):\n")
        for i, item in enumerate(type_data['variants']): f.write(f"{SINGLE_TAB}{item['name'].upper()} = {i}\n")

        f.write("\n\n")

    #Added by me for convienence
    f.write("""class ColorIDs(Enum):
    BG = 1000
    G1 = 1001
    LINE = 1002
    _3DL = 1003
    OBJ = 1004
    P1 = 1005
    P2 = 1006
    G2 = 1009
    MG = 1013
    MG2 = 1014


""")