#!-- Autogenerated by ClassGenerator.py at --!#
#!-- 2026-04-28 18:38:27.154573-05:00 --!#

from NeditGD import Object, HSV
from DataTypes import *
from enum import Enum




class Common:
    def __init__(self):
        self._object = Object()

        #Property Types:
        self.id = NInt()    
        self.x = NFloat()    
        self.y = NFloat()    
        self.flip_horiz = NBool()    
        self.flip_vert = NBool()    
        self.rotation = NFloat()    
        self.scale = NFloat()    
        self.scale_x = NFloat()    
        self.scale_y = NFloat()    
        self.warp_y_angle = NFloat()    
        self.warp_x_angle = NFloat()    
        self.color_1point9 = Color1P9()    
        self.color_1 = NInt()    
        self.color_2 = NInt()    
        self.single_color_type = SingleColorType()    
        self.color_1_hsv_enabled = NBool()    
        self.color_1_hsv = HSVString()    
        self.color_2_hsv_enabled = NBool()    
        self.color_2_hsv = HSVString()    
        self.color_1_index = NInt()    
        self.color_2_index = NInt()    
        self.single_group = NInt()    
        self.groups = GroupList()    
        self.parent_groups = GroupList()    
        self.editor_layer = NInt()    
        self.editor_layer_2 = NInt()    
        self.z_layer = NInt()    
        self.z_order = NInt()    
        self.ord = NInt()    
        self.channel = NInt()    
        self.preview = NBool()    
        self.linked_group = NInt()    
        self.interactible = NBool()    
        self.dont_fade = NBool()    
        self.dont_enter = NBool()    
        self.no_effects = NBool()    
        self.group_parent = NBool()    
        self.area_parent = NBool()    
        self.dont_boost_x = NBool()    
        self.dont_boost_y = NBool()    
        self.single_ptouch = NBool()    
        self.high_detail = NBool()    
        self.no_touch = NBool()    
        self.passable = NBool()    
        self.hide = NBool()    
        self.non_stick_x = NBool()    
        self.non_stick_y = NBool()    
        self.extra_sticky = NBool()    
        self.extended_collision = NBool()    
        self.center_effect = NBool()    
        self.ice_block = NBool()    
        self.grip_slope = NBool()    
        self.no_glow = NBool()    
        self.no_particle = NBool()    
        self.scale_stick = NBool()    
        self.no_audio_scale = NBool()    
        self.reverse = NBool()    
        self.enter_channel = NInt()    
        self.material = NInt()    
        self.control_id = NInt()    #Actual type is ControlID()
        self.orange_tp_portal_distance = NFloat()    
        self.multi_activate_classic = NBool()    
        self.no_multi_activate_platformer = NBool()    

        #Property IDs:
        self._id = 1
        self._x = 2
        self._y = 3
        self._flip_horiz = 4
        self._flip_vert = 5
        self._rotation = 6
        self._scale = 32
        self._scale_x = 128
        self._scale_y = 129
        self._warp_y_angle = 131
        self._warp_x_angle = 132
        self._color_1point9 = 19
        self._color_1 = 21
        self._color_2 = 22
        self._single_color_type = 497
        self._color_1_hsv_enabled = 41
        self._color_1_hsv = 43
        self._color_2_hsv_enabled = 42
        self._color_2_hsv = 44
        self._color_1_index = 155
        self._color_2_index = 156
        self._single_group = 33
        self._groups = 57
        self._parent_groups = 274
        self._editor_layer = 20
        self._editor_layer_2 = 61
        self._z_layer = 24
        self._z_order = 25
        self._ord = 115
        self._channel = 170
        self._preview = 13
        self._linked_group = 108
        self._interactible = 36
        self._dont_fade = 64
        self._dont_enter = 67
        self._no_effects = 116
        self._group_parent = 34
        self._area_parent = 279
        self._dont_boost_x = 509
        self._dont_boost_y = 496
        self._single_ptouch = 284
        self._high_detail = 103
        self._no_touch = 121
        self._passable = 134
        self._hide = 135
        self._non_stick_x = 136
        self._non_stick_y = 289
        self._extra_sticky = 495
        self._extended_collision = 511
        self._center_effect = 369
        self._ice_block = 137
        self._grip_slope = 193
        self._no_glow = 96
        self._no_particle = 507
        self._scale_stick = 356
        self._no_audio_scale = 372
        self._reverse = 117
        self._enter_channel = 343
        self._material = 446
        self._control_id = 534
        self._orange_tp_portal_distance = 54
        self._multi_activate_classic = 99
        self._no_multi_activate_platformer = 444


class DashOrb(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.speed = NFloat()    
        self.end_boost = NFloat()    
        self.max_duration = NFloat()    
        self.allow_collide = NBool()    
        self.stop_slide = NBool()    

        #Property IDs:
        self._speed = 586
        self._end_boost = 588
        self._max_duration = 590
        self._allow_collide = 587
        self._stop_slide = 589


class CustomParticles(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.particle_data = ParticleString()    
        self.use_obj_color = NBool()    
        self.uniform_obj_color = NBool()    
        self.animate_on_trigger = NBool()    
        self.animate_active_only = NBool()    
        self.quick_start = NBool()    

        #Property IDs:
        self._particle_data = 145
        self._use_obj_color = 146
        self._uniform_obj_color = 147
        self._animate_on_trigger = 123
        self._animate_active_only = 214
        self._quick_start = 211


class TextObject(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.text = String()    
        self.kerning = NInt()    

        #Property IDs:
        self._text = 31
        self._kerning = 488


class Collectible(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.particle = NInt()    
        self.points = NInt()    
        self.toggle_trigger = NBool()    
        self.group_id = NInt()    #Actual type is GroupID()
        self.enable_group = NBool()    
        self.pickup_item = NBool()    
        self.item_id = NInt()    #Actual type is ItemID()
        self.sub_count = NBool()    
        self.no_anim = NBool()    

        #Property IDs:
        self._particle = 440
        self._points = 383
        self._toggle_trigger = 382
        self._group_id = 51
        self._enable_group = 56
        self._pickup_item = 381
        self._item_id = 80
        self._sub_count = 78
        self._no_anim = 463


class RotatingObject(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.rotation_speed = NFloat()    
        self.disable_rotation = NBool()    

        #Property IDs:
        self._rotation_speed = 97
        self._disable_rotation = 98


class AnimatedObject(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.randomize_start = NBool()    
        self.disable_delayed_loop = NBool()    
        self.use_speed = NBool()    
        self.speed = NFloat()    
        self.disable_animshine = NBool()    
        self.animate_on_trigger = NBool()    
        self.only_if_active = NBool()    
        self.single_frame = NInt()    
        self.offset_anim = NBool()    

        #Property IDs:
        self._randomize_start = 106
        self._disable_delayed_loop = 126
        self._use_speed = 122
        self._speed = 107
        self._disable_animshine = 127
        self._animate_on_trigger = 123
        self._only_if_active = 214
        self._single_frame = 462
        self._offset_anim = 592


class KeyframeObject(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.group_id = NInt()    #Actual type is GroupID()
        self.x360 = NInt()    
        self.spawn_gid = NInt()    #Actual type is GroupID()
        self.spawn_delay = NFloat()    
        self.curve = NBool()    
        self.cw_ccw = KeyframeRotDir()    
        self.time_even_dist = KeyframeMode()    
        self.prox = NBool()    
        self.ref_only = NBool()    
        self.auto_layer = NBool()    
        self.preview_art = NBool()    
        self.close_loop = NBool()    
        self.anim_id = NInt()    
        self.order_index = NInt()    
        self.line_opacity = NFloat()    

        #Property IDs:
        self._duration = 10
        self._group_id = 51
        self._x360 = 537
        self._spawn_gid = 71
        self._spawn_delay = 557
        self._curve = 378
        self._cw_ccw = 536
        self._time_even_dist = 379
        self._prox = 377
        self._ref_only = 375
        self._auto_layer = 459
        self._preview_art = 380
        self._close_loop = 376
        self._anim_id = 373
        self._order_index = 374
        self._line_opacity = 524


class Trigger(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.spawn_triggered = NBool()    
        self.touch_triggered = NBool()    
        self.multi_triggered = NBool()    
        self.easing = Easing()    
        self.easing_rate = NFloat()    
        self.ignore_linked = NBool()    
        self.ignore_gparent = NBool()    

        #Property IDs:
        self._spawn_triggered = 62
        self._touch_triggered = 11
        self._multi_triggered = 87
        self._easing = 30
        self._easing_rate = 85
        self._ignore_linked = 281
        self._ignore_gparent = 280


class ColorTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.red = NInt()    
        self.green = NInt()    
        self.blue = NInt()    
        self.opacity = NFloat()    
        self.blending = NBool()    
        self.player_color_1 = NBool()    
        self.player_color_2 = NBool()    
        self.target_color = NInt()    #Actual type is ColorID()
        self.copy_color_id = NInt()    #Actual type is ColorID()
        self.legacy_hsv_off = NBool()    
        self.hsv = HSVString()    
        self.copy_opacity = NBool()    

        #Property IDs:
        self._duration = 10
        self._red = 7
        self._green = 8
        self._blue = 9
        self._opacity = 35
        self._blending = 17
        self._player_color_1 = 15
        self._player_color_2 = 16
        self._target_color = 23
        self._copy_color_id = 50
        self._legacy_hsv_off = 210
        self._hsv = 49
        self._copy_opacity = 60


class BackgroundColorTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.tint_ground = NBool()    

        #Property IDs:
        self._duration = 10
        self._tint_ground = 14


class BackgroundSpeedTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.mod_x = NFloat()    
        self.mod_y = NFloat()    

        #Property IDs:
        self._mod_x = 143
        self._mod_y = 144


class MiddleGroundSpeedTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.mod_x = NFloat()    
        self.mod_y = NFloat()    

        #Property IDs:
        self._mod_x = 143
        self._mod_y = 144


class EditMiddleGroundTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.offset = NInt()    

        #Property IDs:
        self._duration = 10
        self._offset = 29


class MoveTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.target_group = NInt()    #Actual type is GroupID()
        self.move_x = NInt()    
        self.move_y = NInt()    
        self.lock_x_player = NBool()    
        self.lock_y_player = NBool()    
        self.mod_x = NFloat()    
        self.mod_y = NFloat()    
        self.lock_x_camera = NBool()    
        self.lock_y_camera = NBool()    
        self.target_mode = NBool()    
        self.mode_center_group = NInt()    #Actual type is GroupID()
        self.mode_target_group = NInt()    #Actual type is GroupID()
        self.mode_target_p1 = NBool()    
        self.mode_target_p2 = NBool()    
        self.mode_xy_only = XYOnly()    
        self.direction_mode = NBool()    
        self.direction_mode_distance = NInt()    
        self.silent = NBool()    
        self.dynamic_mode = NBool()    
        self.small_step = NBool()    

        #Property IDs:
        self._duration = 10
        self._target_group = 51
        self._move_x = 28
        self._move_y = 29
        self._lock_x_player = 58
        self._lock_y_player = 59
        self._mod_x = 143
        self._mod_y = 144
        self._lock_x_camera = 141
        self._lock_y_camera = 142
        self._target_mode = 100
        self._mode_center_group = 395
        self._mode_target_group = 71
        self._mode_target_p1 = 138
        self._mode_target_p2 = 200
        self._mode_xy_only = 101
        self._direction_mode = 394
        self._direction_mode_distance = 396
        self._silent = 544
        self._dynamic_mode = 397
        self._small_step = 393


class PulseTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_id = NInt()    #Actual type is ColorOrGroupID()
        self.target_type = NBool()    
        self.exclusive = NBool()    
        self.main_only = NBool()    
        self.detail_only = NBool()    
        self.fade_in = NFloat()    
        self.hold = NFloat()    
        self.fade_out = NFloat()    
        self.red = NInt()    
        self.green = NInt()    
        self.blue = NInt()    
        self.hsv_enabled = NBool()    
        self.hsv = HSVString()    
        self.copy_color_id = NInt()    #Actual type is ColorID()
        self.static_hsv_off = NBool()    

        #Property IDs:
        self._target_id = 51
        self._target_type = 52
        self._exclusive = 86
        self._main_only = 65
        self._detail_only = 66
        self._fade_in = 45
        self._hold = 46
        self._fade_out = 47
        self._red = 7
        self._green = 8
        self._blue = 9
        self._hsv_enabled = 48
        self._hsv = 49
        self._copy_color_id = 50
        self._static_hsv_off = 210


class AlphaTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.target_group = NInt()    #Actual type is GroupID()
        self.opacity = NFloat()    

        #Property IDs:
        self._duration = 10
        self._target_group = 51
        self._opacity = 35


class ToggleTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_group = NInt()    #Actual type is GroupID()
        self.activate_group = NBool()    

        #Property IDs:
        self._target_group = 51
        self._activate_group = 56


class ShakeTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.strength = NFloat()    
        self.interval = NFloat()    

        #Property IDs:
        self._duration = 10
        self._strength = 75
        self._interval = 84


class AnimateTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_group = NInt()    #Actual type is GroupID()
        self.animation_id = NInt()    

        #Property IDs:
        self._target_group = 51
        self._animation_id = 76


class SpawnTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_group = NInt()    #Actual type is GroupID()
        self.delay = NFloat()    
        self.delay_pm = NFloat()    
        self.preview_disable = NBool()    
        self.spawn_ordered = NBool()    
        self.reset_remap = NBool()    
        self.group_remaps = RemapList()    

        #Property IDs:
        self._target_group = 51
        self._delay = 63
        self._delay_pm = 556
        self._preview_disable = 102
        self._spawn_ordered = 441
        self._reset_remap = 581
        self._group_remaps = 442


class RotateTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.degrees = NFloat()    
        self.x360 = NInt()    
        self.target_group = NInt()    #Actual type is GroupID()
        self.center_group = NInt()    #Actual type is GroupID()
        self.aim_mode = NBool()    
        self.follow_mode = NBool()    
        self.rot_target_id = NInt()    
        self.rot_offset = NFloat()    
        self.mode_target_p1 = NBool()    
        self.mode_target_p2 = NBool()    
        self.dynamic_mode = NBool()    
        self.dynamic_mode_easing = NInt()    
        self.lock_obj_rot = NBool()    
        self.min_x_id = NInt()    #Actual type is GroupID()
        self.min_y_id = NInt()    #Actual type is GroupID()
        self.max_x_id = NInt()    #Actual type is GroupID()
        self.max_y_id = NInt()    #Actual type is GroupID()

        #Property IDs:
        self._duration = 10
        self._degrees = 68
        self._x360 = 69
        self._target_group = 51
        self._center_group = 71
        self._aim_mode = 100
        self._follow_mode = 394
        self._rot_target_id = 401
        self._rot_offset = 402
        self._mode_target_p1 = 138
        self._mode_target_p2 = 200
        self._dynamic_mode = 397
        self._dynamic_mode_easing = 403
        self._lock_obj_rot = 70
        self._min_x_id = 516
        self._min_y_id = 517
        self._max_x_id = 518
        self._max_y_id = 519


class ScaleTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.scale_trigger_scale_x = NFloat()    
        self.scale_trigger_scale_y = NFloat()    
        self.div_x = NBool()    
        self.div_y = NBool()    
        self.target_group = NInt()    #Actual type is GroupID()
        self.center_group = NInt()    #Actual type is GroupID()
        self.only_move = NBool()    
        self.relative_scale = NBool()    
        self.relative_rot = NBool()    

        #Property IDs:
        self._duration = 10
        self._scale_trigger_scale_x = 150
        self._scale_trigger_scale_y = 151
        self._div_x = 153
        self._div_y = 154
        self._target_group = 51
        self._center_group = 71
        self._only_move = 133
        self._relative_scale = 577
        self._relative_rot = 452


class FollowTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.move_time = NFloat()    
        self.x_mod = NFloat()    
        self.y_mod = NFloat()    
        self.target_group = NInt()    #Actual type is GroupID()
        self.follow_group = NInt()    #Actual type is GroupID()

        #Property IDs:
        self._move_time = 10
        self._x_mod = 72
        self._y_mod = 73
        self._target_group = 51
        self._follow_group = 71


class StopTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_group = NInt()    #Actual type is GroupOrControlID()
        self.use_control_id = NBool()    
        self.stop_pause_resume = StopMode()    

        #Property IDs:
        self._target_group = 51
        self._use_control_id = 535
        self._stop_pause_resume = 580


class KeyframeAnimTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.animation_group_id = NInt()    #Actual type is GroupID()
        self.target_group = NInt()    #Actual type is GroupID()
        self.parent_group = NInt()    #Actual type is GroupID()
        self.time_mod = NFloat()    
        self.position_x_mod = NFloat()    
        self.position_y_mod = NFloat()    
        self.rotation_mod = NFloat()    
        self.scale_x_mod = NFloat()    
        self.scale_y_mod = NFloat()    

        #Property IDs:
        self._animation_group_id = 76
        self._target_group = 51
        self._parent_group = 71
        self._time_mod = 520
        self._position_x_mod = 521
        self._position_y_mod = 545
        self._rotation_mod = 522
        self._scale_x_mod = 523
        self._scale_y_mod = 546


class FollowPlayerYTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.move_time = NFloat()    
        self.speed = NFloat()    
        self.delay = NFloat()    
        self.offset = NInt()    
        self.max_speed = NFloat()    
        self.target_group = NInt()    #Actual type is GroupID()

        #Property IDs:
        self._move_time = 10
        self._speed = 90
        self._delay = 91
        self._offset = 92
        self._max_speed = 105
        self._target_group = 51


class AdvancedFollowTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_group = NInt()    #Actual type is GroupID()
        self.follow_group = NInt()    #Actual type is GroupID()
        self.priority = NInt()    
        self.x_only = NBool()    
        self.y_only = NBool()    
        self.follow_p1 = NBool()    
        self.follow_p2 = NBool()    
        self.follow_c = NBool()    
        self.rot_offset = NInt()    
        self.rot_easing = NInt()    
        self.rot_dead_z = NInt()    
        self.ignore_disabled = NBool()    
        self.rotate_dir = NBool()    
        self.init_set_add = AdvancedFollowMode()    
        self.exclusive = NBool()    
        self.page_2_mode = AdvancedFollowPage2Mode()    
        self.delay = NFloat()    
        self.delay_pm = NFloat()    
        self.max_speed = NFloat()    
        self.max_speed_pm = NFloat()    
        self.max_range = NInt()    
        self.max_range_pm = NInt()    
        self.max_range_unmarked = NInt()    
        self.follow_easing = NFloat()    
        self.follow_easing_pm = NFloat()    
        self.start_speed = NFloat()    
        self.start_speed_pm = NFloat()    
        self.start_speed_unmarked = NInt()    
        self.start_dir = NInt()    
        self.start_dir_pm = NInt()    
        self.start_dir_unmarked = NInt()    
        self.acceleration = NFloat()    
        self.acceleration_pm = NFloat()    
        self.friction = NFloat()    
        self.friction_pm = NFloat()    
        self.near_dist = NFloat()    
        self.near_dist_pm = NFloat()    
        self.near_friction = NFloat()    
        self.near_friction_pm = NFloat()    
        self.near_accel = NFloat()    
        self.near_accel_pm = NFloat()    
        self.steer_force = NFloat()    
        self.steer_force_pm = NFloat()    
        self.steer_force_low = NFloat()    
        self.steer_force_low_pm = NFloat()    
        self.steer_force_low_checkbox = NBool()    
        self.speed_range_low = NFloat()    
        self.speed_range_low_pm = NFloat()    
        self.steer_force_high = NFloat()    
        self.steer_force_high_pm = NFloat()    
        self.steer_force_high_checkbox = NBool()    
        self.speed_range_high = NFloat()    
        self.speed_range_high_pm = NFloat()    
        self.slow_dist = NInt()    
        self.slow_dist_pm = NInt()    
        self.break_force = NFloat()    
        self.break_force_pm = NFloat()    
        self.break_angle = NInt()    
        self.break_angle_pm = NInt()    
        self.break_steer_force = NFloat()    
        self.break_steer_force_pm = NFloat()    
        self.break_steer_speed_limit = NFloat()    
        self.break_steer_speed_limit_pm = NFloat()    
        self.target_dir = NBool()    

        #Property IDs:
        self._target_group = 51
        self._follow_group = 71
        self._priority = 365
        self._x_only = 306
        self._y_only = 307
        self._follow_p1 = 138
        self._follow_p2 = 200
        self._follow_c = 201
        self._rot_offset = 340
        self._rot_easing = 363
        self._rot_dead_z = 364
        self._ignore_disabled = 336
        self._rotate_dir = 339
        self._init_set_add = 572
        self._exclusive = 571
        self._page_2_mode = 367
        self._delay = 292
        self._delay_pm = 293
        self._max_speed = 298
        self._max_speed_pm = 299
        self._max_range = 308
        self._max_range_pm = 309
        self._max_range_unmarked = 366
        self._follow_easing = 361
        self._follow_easing_pm = 362
        self._start_speed = 300
        self._start_speed_pm = 301
        self._start_speed_unmarked = 560
        self._start_dir = 563
        self._start_dir_pm = 564
        self._start_dir_unmarked = 565
        self._acceleration = 334
        self._acceleration_pm = 335
        self._friction = 558
        self._friction_pm = 559
        self._near_dist = 359
        self._near_dist_pm = 360
        self._near_friction = 561
        self._near_friction_pm = 562
        self._near_accel = 357
        self._near_accel_pm = 358
        self._steer_force = 316
        self._steer_force_pm = 317
        self._steer_force_low = 318
        self._steer_force_low_pm = 319
        self._steer_force_low_checkbox = 337
        self._speed_range_low = 322
        self._speed_range_low_pm = 323
        self._steer_force_high = 320
        self._steer_force_high_pm = 321
        self._steer_force_high_checkbox = 338
        self._speed_range_high = 324
        self._speed_range_high_pm = 325
        self._slow_dist = 359
        self._slow_dist_pm = 360
        self._break_force = 326
        self._break_force_pm = 327
        self._break_angle = 328
        self._break_angle_pm = 329
        self._break_steer_force = 330
        self._break_steer_force_pm = 331
        self._break_steer_speed_limit = 332
        self._break_steer_speed_limit_pm = 333
        self._target_dir = 305


class EditAdvancedFollowTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_group = NInt()    #Actual type is GroupOrControlID()
        self.x_only = NBool()    
        self.y_only = NBool()    
        self.mod_x = NFloat()    
        self.mod_x_pm = NFloat()    
        self.mod_y = NFloat()    
        self.mod_y_pm = NFloat()    
        self.speed = NFloat()    
        self.speed_pm = NFloat()    
        self.speed_unmarked = NInt()    
        self.dir = NInt()    
        self.dir_pm = NInt()    
        self.dir_unmarked = NInt()    
        self.target_control_id = NBool()    
        self.redirect_dir = NBool()    

        #Property IDs:
        self._target_group = 51
        self._x_only = 306
        self._y_only = 307
        self._mod_x = 566
        self._mod_x_pm = 567
        self._mod_y = 568
        self._mod_y_pm = 569
        self._speed = 300
        self._speed_pm = 301
        self._speed_unmarked = 560
        self._dir = 363
        self._dir_pm = 364
        self._dir_unmarked = 565
        self._target_control_id = 535
        self._redirect_dir = 570


class RetargetAdvancedFollowTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_group = NInt()    #Actual type is GroupOrControlID()
        self.follow_group = NInt()    #Actual type is GroupID()
        self.target_control_id = NBool()    
        self.follow_p1 = NBool()    
        self.follow_p2 = NBool()    
        self.follow_c = NBool()    

        #Property IDs:
        self._target_group = 51
        self._follow_group = 71
        self._target_control_id = 535
        self._follow_p1 = 138
        self._follow_p2 = 200
        self._follow_c = 201


class AreaEditAreaTriggerCommon:
    def __init__(self):
        #Property Types:
        self.length = NInt()    
        self.length_pm = NInt()    
        self.offset = NInt()    
        self.offset_pm = NInt()    
        self.offset_y = NInt()    
        self.offset_y_pm = NInt()    
        self.mod_front = NFloat()    
        self.mod_back = NFloat()    
        self.deadzone = NFloat()    
        self.area_easing = Easing()    
        self.area_easing_rate = NFloat()    

        #Property IDs:
        self._length = 222
        self._length_pm = 223
        self._offset = 220
        self._offset_pm = 221
        self._offset_y = 252
        self._offset_y_pm = 253
        self._mod_front = 263
        self._mod_back = 264
        self._deadzone = 282
        self._area_easing = 242
        self._area_easing_rate = 243


class AreaTrigger(AreaEditAreaTriggerCommon, Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.ease_out = NBool()    
        self.area_easing2 = Easing()    
        self.area_easing2_rate = NFloat()    
        self.dir_buttons_dir = AreaDirButtonsDir()    
        self.dir_buttons_inwards = NBool()    
        self.dir_buttons_double_arrow = NBool()    
        self.de_ap = NBool()    
        self.effect_id = NInt()    #Actual type is EffectID()
        self.target_group = NInt()    #Actual type is GroupID()
        self.center_group = NInt()    #Actual type is GroupID()
        self.priority = NInt()    
        self.center_special = AreaCenterSpecial()    

        #Property IDs:
        self._ease_out = 261
        self._area_easing2 = 248
        self._area_easing2_rate = 249
        self._dir_buttons_dir = 262
        self._dir_buttons_inwards = 276
        self._dir_buttons_double_arrow = 283
        self._de_ap = 539
        self._effect_id = 225
        self._target_group = 51
        self._center_group = 71
        self._priority = 341
        self._center_special = 538


class EditAreaTrigger(AreaEditAreaTriggerCommon, Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.group_effect_id = NInt()    #Actual type is GroupOrEffectID()
        self.use_eid = NBool()    
        self.unknown = NFloat()    

        #Property IDs:
        self._duration = 10
        self._group_effect_id = 51
        self._use_eid = 255
        self._unknown = 285


class AreaMoveTriggerCommon:
    def __init__(self):
        #Property Types:
        self.move_dist = NInt()    
        self.move_dist_pm = NInt()    
        self.move_angle = NInt()    
        self.move_angle_pm = NInt()    
        self.rfade = NFloat()    
        self.xy_mode = NBool()    
        self.move_x = NInt()    
        self.move_x_pm = NInt()    
        self.move_y = NInt()    
        self.move_y_pm = NInt()    

        #Property IDs:
        self._move_dist = 218
        self._move_dist_pm = 219
        self._move_angle = 231
        self._move_angle_pm = 232
        self._rfade = 288
        self._xy_mode = 241
        self._move_x = 237
        self._move_x_pm = 238
        self._move_y = 239
        self._move_y_pm = 240


class AreaMoveTrigger(AreaMoveTriggerCommon, AreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.relative = NBool()    

        #Property IDs:
        self._relative = 287


class EditAreaMoveTrigger(AreaMoveTriggerCommon, EditAreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class AreaRotateTriggerCommon:
    def __init__(self):
        #Property Types:
        self.area_rotation = NFloat()    
        self.area_rotation_pm = NFloat()    

        #Property IDs:
        self._area_rotation = 270
        self._area_rotation_pm = 271


class AreaRotateTrigger(AreaRotateTriggerCommon, AreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class EditAreaRotateTrigger(AreaRotateTriggerCommon, EditAreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class AreaScaleTriggerCommon:
    def __init__(self):
        #Property Types:
        self.area_scale_x = NFloat()    
        self.area_scale_x_pm = NFloat()    
        self.area_scale_y = NFloat()    
        self.area_scale_y_pm = NFloat()    

        #Property IDs:
        self._area_scale_x = 233
        self._area_scale_x_pm = 234
        self._area_scale_y = 235
        self._area_scale_y_pm = 236


class AreaScaleTrigger(AreaScaleTriggerCommon, AreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class EditAreaScaleTrigger(AreaScaleTriggerCommon, EditAreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class AreaFadeTriggerCommon:
    def __init__(self):
        #Property Types:
        self.to_opacity = NFloat()    

        #Property IDs:
        self._to_opacity = 275


class AreaFadeTrigger(AreaFadeTriggerCommon, AreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.from_opacity = NFloat()    

        #Property IDs:
        self._from_opacity = 286


class EditAreaFadeTrigger(AreaFadeTriggerCommon, EditAreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class AreaTintTriggerCommon:
    def __init__(self):
        #Property Types:
        self.tint = NFloat()    
        self.hsv_on = NBool()    
        self.hsv = HSVString()    

        #Property IDs:
        self._tint = 265
        self._hsv_on = 278
        self._hsv = 49


class AreaTintTrigger(AreaTintTriggerCommon, AreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.color_channel = NInt()    #Actual type is ColorID()
        self.main_only = NBool()    
        self.secondary_only = NBool()    

        #Property IDs:
        self._color_channel = 260
        self._main_only = 65
        self._secondary_only = 66


class EditAreaTintTrigger(AreaTintTriggerCommon, EditAreaTrigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class StopAreaTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.effect_id = NInt()    

        #Property IDs:
        self._effect_id = 51


class BackgroundTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.background = Background()    

        #Property IDs:
        self._background = 533


class GroundTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.ground = Ground()    

        #Property IDs:
        self._ground = 533


class MiddleGroundTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.middle_ground = MiddleGround()    

        #Property IDs:
        self._middle_ground = 533


class TouchTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_group = NInt()    #Actual type is GroupID()
        self.hold_mode = NBool()    
        self.p1_p2_only = TouchPlayerOnly()    
        self.toggle_on_off = TouchToggle()    
        self.dual_mode = NBool()    

        #Property IDs:
        self._target_group = 51
        self._hold_mode = 81
        self._p1_p2_only = 198
        self._toggle_on_off = 82
        self._dual_mode = 89


class CountTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.item_id = NInt()    #Actual type is ItemID()
        self.target_group = NInt()    #Actual type is GroupID()
        self.target_count = NInt()    
        self.activate_group = NBool()    
        self.multi_activate = NBool()    

        #Property IDs:
        self._item_id = 80
        self._target_group = 51
        self._target_count = 77
        self._activate_group = 56
        self._multi_activate = 104


class InstantCountTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.item_id = NInt()    #Actual type is ItemID()
        self.target_group = NInt()    #Actual type is GroupID()
        self.target_count = NInt()    
        self.activate_group = NBool()    
        self.comparison = InstantCountComparison()    

        #Property IDs:
        self._item_id = 80
        self._target_group = 51
        self._target_count = 77
        self._activate_group = 56
        self._comparison = 88


class GradientTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.blending = GradientBlend()    
        self.layer = TriggerLayer()    
        self.u_bl = NInt()    
        self.d_br = NInt()    
        self.l_tl = NInt()    
        self.r_tr = NInt()    
        self.vertex_mode = NBool()    
        self.disable = NBool()    
        self.gradient_id = NInt()    
        self.preview_opacity = NFloat()    
        self.disable_all = NBool()    

        #Property IDs:
        self._blending = 174
        self._layer = 202
        self._u_bl = 203
        self._d_br = 204
        self._l_tl = 205
        self._r_tr = 206
        self._vertex_mode = 207
        self._disable = 208
        self._gradient_id = 209
        self._preview_opacity = 456
        self._disable_all = 508


class StaticCameraTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.duration = NFloat()    
        self.target_group = NInt()    
        self.follow = NBool()    
        self.follow_easing = NFloat()    
        self.smooth_velocity = NBool()    
        self.smooth_velocity_modifier = NFloat()    
        self.exit_instant = NBool()    
        self.exit_static = NBool()    

        #Property IDs:
        self._duration = 10
        self._target_group = 71
        self._follow = 212
        self._follow_easing = 213
        self._smooth_velocity = 453
        self._smooth_velocity_modifier = 454
        self._exit_instant = 465
        self._exit_static = 110


class CameraZoomTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.time = NFloat()    
        self.zoom = NFloat()    

        #Property IDs:
        self._time = 10
        self._zoom = 371


class CameraRotateTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.move_time = NFloat()    
        self.degrees = NFloat()    
        self.add = NBool()    
        self.snap360 = NBool()    

        #Property IDs:
        self._move_time = 10
        self._degrees = 68
        self._add = 70
        self._snap360 = 394


class CameraEdgeTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.edge = CameraEdge()    
        self.target_group = NInt()    #Actual type is GroupID()

        #Property IDs:
        self._edge = 164
        self._target_group = 51


class CameraModeTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.free_mode = NBool()    
        self.edit_camera_settings = NBool()    
        self.camera_easing = NInt()    
        self.padding = NFloat()    
        self.disable_gridsnap = NBool()    

        #Property IDs:
        self._free_mode = 111
        self._edit_camera_settings = 112
        self._camera_easing = 113
        self._padding = 114
        self._disable_gridsnap = 370


class CameraGuide(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.zoom = NFloat()    
        self.offset_x = NInt()    
        self.offset_y = NInt()    
        self.preview_opacity = NFloat()    

        #Property IDs:
        self._zoom = 371
        self._offset_x = 28
        self._offset_y = 29
        self._preview_opacity = 506


class CameraOffsetTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.move_time = NFloat()    
        self.offset_x = NInt()    
        self.offset_y = NInt()    
        self.xy_only = XYOnly()    

        #Property IDs:
        self._move_time = 10
        self._offset_x = 28
        self._offset_y = 29
        self._xy_only = 101


class SongTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.volume = NFloat()    
        self.speed = NInt()    
        self.song_channel = NInt()    
        self.loop = NBool()    
        self.start = NInt()    
        self.fade_in = NInt()    
        self.end = NInt()    
        self.fade_out = NInt()    
        self.prep = NBool()    
        self.load_prep = NBool()    
        self.song = NInt()    
        self.dont_reset = NBool()    

        #Property IDs:
        self._volume = 406
        self._speed = 404
        self._song_channel = 432
        self._loop = 413
        self._start = 408
        self._fade_in = 409
        self._end = 410
        self._fade_out = 411
        self._prep = 399
        self._load_prep = 400
        self._song = 392
        self._dont_reset = 595


class SFXTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.sfx_id = NInt()    
        self.sound_duration = NFloat()    
        self.speed = NInt()    
        self.pitch = NInt()    
        self.volume = NFloat()    
        self.reverb = NBool()    
        self.reverb_type = ReverbType()    
        self.reverb_enable = NBool()    
        self.fft = NBool()    
        self.loop = NBool()    
        self.pre_load = NBool()    
        self.start = NInt()    
        self.end = NInt()    
        self.fade_in = NInt()    
        self.fade_out = NInt()    
        self.unique_id = NInt()    #Actual type is UniqueID()
        self.sfx_group = NInt()    #Actual type is SFXGroup()
        self.is_unique = NBool()    
        self.override = NBool()    
        self.min_interval = NFloat()    
        self.ignore_volume_test = NBool()    
        self.group_id_1 = NInt()    
        self.group_id_2 = NInt()    
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.cam = NBool()    
        self.vol_near = NFloat()    
        self.vol_med = NFloat()    
        self.vol_far = NFloat()    
        self.min_dist = NInt()    
        self.dist_2 = NInt()    
        self.dist_3 = NInt()    
        self.dir_buttons = SoundDirs()    
        self.speed_pm = NInt()    
        self.pitch_pm = NInt()    
        self.volume_pm = NFloat()    
        self.pitch_steps = NBool()    

        #Property IDs:
        self._sfx_id = 392
        self._sound_duration = 490
        self._speed = 404
        self._pitch = 405
        self._volume = 406
        self._reverb = 407
        self._reverb_type = 502
        self._reverb_enable = 503
        self._fft = 412
        self._loop = 413
        self._pre_load = 433
        self._start = 408
        self._end = 410
        self._fade_in = 409
        self._fade_out = 411
        self._unique_id = 416
        self._sfx_group = 455
        self._is_unique = 415
        self._override = 420
        self._min_interval = 434
        self._ignore_volume_test = 489
        self._group_id_1 = 51
        self._group_id_2 = 71
        self._p1 = 138
        self._p2 = 200
        self._cam = 428
        self._vol_near = 421
        self._vol_med = 422
        self._vol_far = 423
        self._min_dist = 424
        self._dist_2 = 425
        self._dist_3 = 426
        self._dir_buttons = 458
        self._speed_pm = 596
        self._pitch_pm = 597
        self._volume_pm = 598
        self._pitch_steps = 599


class PickupTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.item_id = NInt()    #Actual type is ItemID()
        self.count = NInt()    
        self.override = NBool()    
        self.multiply_divide = PickupMultiplyDivide()    
        self.modifier = NFloat()    

        #Property IDs:
        self._item_id = 80
        self._count = 77
        self._override = 139
        self._multiply_divide = 88
        self._modifier = 449


class TimeTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.start_time = NFloat()    
        self.stop_time = NFloat()    
        self.stop_checked = NBool()    
        self.item_id = NInt()    #Actual type is TimerID()
        self.target_id = NInt()    #Actual type is GroupID()
        self.time_mod = NFloat()    
        self.ignore_timewarp = NBool()    
        self.start_paused = NBool()    
        self.dont_override = NBool()    

        #Property IDs:
        self._start_time = 467
        self._stop_time = 473
        self._stop_checked = 474
        self._item_id = 80
        self._target_id = 51
        self._time_mod = 470
        self._ignore_timewarp = 469
        self._start_paused = 471
        self._dont_override = 468


class TimeEventTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.item_id = NInt()    #Actual type is TimerID()
        self.target_id = NInt()    #Actual type is GroupID()
        self.target_time = NFloat()    
        self.multi_activate = NBool()    

        #Property IDs:
        self._item_id = 80
        self._target_id = 51
        self._target_time = 473
        self._multi_activate = 475


class TimeControlTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.item_id = NInt()    
        self.start_stop = NBool()    

        #Property IDs:
        self._item_id = 80
        self._start_stop = 472


class ItemEditTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.item_id_1 = NInt()    #Actual type is ItemOrTimerID()
        self.item_id_2 = NInt()    #Actual type is ItemOrTimerID()
        self.target_item_id = NInt()    #Actual type is ItemOrTimerID()
        self.typ_1 = ItemTriggerTyp()    
        self.typ_2 = ItemTriggerTyp()    
        self.target_typ = ItemTriggerTyp()    
        self.mod = NFloat()    
        self.assign_op = ItemTriggerOp()    
        self.op_1 = ItemTriggerOp()    
        self.op_2 = ItemTriggerOp()    
        self.abs_neg_1 = ItemTriggerAbsNeg()    
        self.abs_neg_2 = ItemTriggerAbsNeg()    
        self.rounding_1 = ItemTriggerRounding()    
        self.rounding_2 = ItemTriggerRounding()    

        #Property IDs:
        self._item_id_1 = 80
        self._item_id_2 = 95
        self._target_item_id = 51
        self._typ_1 = 476
        self._typ_2 = 477
        self._target_typ = 478
        self._mod = 479
        self._assign_op = 480
        self._op_1 = 481
        self._op_2 = 482
        self._abs_neg_1 = 578
        self._abs_neg_2 = 579
        self._rounding_1 = 485
        self._rounding_2 = 486


class ItemCompareTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.item_id_1 = NInt()    #Actual type is ItemOrTimerID()
        self.item_id_2 = NInt()    #Actual type is ItemOrTimerID()
        self.typ_1 = ItemTriggerTyp()    
        self.typ_2 = ItemTriggerTyp()    
        self.mod_1 = NFloat()    
        self.mod_2 = NFloat()    
        self.true_id = NInt()    #Actual type is GroupID()
        self.false_id = NInt()    #Actual type is GroupID()
        self.tol_pm = NFloat()    
        self.op_1 = ItemTriggerOp()    
        self.op_2 = ItemTriggerOp()    
        self.compare_op = ItemTriggerCompareOp()    
        self.abs_neg_1 = ItemTriggerAbsNeg()    
        self.abs_neg_2 = ItemTriggerAbsNeg()    
        self.rounding_1 = ItemTriggerRounding()    
        self.rounding_2 = ItemTriggerRounding()    

        #Property IDs:
        self._item_id_1 = 80
        self._item_id_2 = 95
        self._typ_1 = 476
        self._typ_2 = 477
        self._mod_1 = 479
        self._mod_2 = 483
        self._true_id = 51
        self._false_id = 71
        self._tol_pm = 484
        self._op_1 = 480
        self._op_2 = 481
        self._compare_op = 482
        self._abs_neg_1 = 578
        self._abs_neg_2 = 579
        self._rounding_1 = 485
        self._rounding_2 = 486


class ItemPersistenceTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.item_id = NInt()    #Actual type is ItemOrTimerID()
        self.timer = NBool()    
        self.persistent = NBool()    
        self.target_all = NBool()    
        self.reset = NBool()    

        #Property IDs:
        self._item_id = 80
        self._timer = 494
        self._persistent = 491
        self._target_all = 492
        self._reset = 493


class RandomTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.group_id_1 = NInt()    #Actual type is GroupID()
        self.group_id_2 = NInt()    #Actual type is GroupID()
        self.chance = NFloat()    

        #Property IDs:
        self._group_id_1 = 51
        self._group_id_2 = 71
        self._chance = 10


class AdvancedRandomTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.list = AdvRandomList()    

        #Property IDs:
        self._list = 152


class SequenceTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.sequence = SequenceList()    
        self.mode = SequenceMode()    
        self.min_int = NFloat()    
        self.reset = NFloat()    
        self.reset_full_step = NBool()    
        self.unique_remap = NBool()    

        #Property IDs:
        self._sequence = 435
        self._mode = 436
        self._min_int = 437
        self._reset = 438
        self._reset_full_step = 439
        self._unique_remap = 505


class SpawnParticleTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.particle_group = NInt()    #Actual type is GroupID()
        self.position_group = NInt()    #Actual type is GroupID()
        self.offset_x = NFloat()    
        self.offset_y = NFloat()    
        self.offvar_x = NFloat()    
        self.offvar_y = NFloat()    
        self.particle_rotation = NFloat()    
        self.particle_rotation_pm = NFloat()    
        self.particle_scale = NFloat()    
        self.particle_scale_pm = NFloat()    
        self.match_rot = NBool()    

        #Property IDs:
        self._particle_group = 51
        self._position_group = 71
        self._offset_x = 547
        self._offset_y = 548
        self._offvar_x = 549
        self._offvar_y = 550
        self._particle_rotation = 552
        self._particle_rotation_pm = 553
        self._particle_scale = 554
        self._particle_scale_pm = 555
        self._match_rot = 551


class ResetTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.group_id = NInt()    

        #Property IDs:
        self._group_id = 51


class ArrowTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.edit_velocity = NBool()    
        self.velocity_mod_x = NFloat()    
        self.velocity_mod_y = NFloat()    
        self.override_velocity = NBool()    
        self.change_channel = NBool()    
        self.channel_only = NBool()    
        self.target_channel = NInt()    #Actual type is ChannelID()
        self.dont_slide = NBool()    
        self.instant_offset = NBool()    
        self.arrow_dir = ArrowDir()    
        self.gravity_dir = ArrowDir()    

        #Property IDs:
        self._edit_velocity = 169
        self._velocity_mod_x = 582
        self._velocity_mod_y = 583
        self._override_velocity = 584
        self._change_channel = 171
        self._channel_only = 172
        self._target_channel = 173
        self._dont_slide = 585
        self._instant_offset = 368
        self._arrow_dir = 167
        self._gravity_dir = 166


class EventTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.group_id = NInt()    #Actual type is GroupID()
        self.extra_id = NInt()    
        self.extra_id_2 = NInt()    
        self.events = EventList()    

        #Property IDs:
        self._group_id = 51
        self._extra_id = 447
        self._extra_id_2 = 525
        self._events = 430


class TimewarpTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.time_mod = NFloat()    

        #Property IDs:
        self._time_mod = 120


class CounterLabel(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.item_id = NInt()    #Actual type is ItemOrTimerID()
        self.time_counter = NBool()    
        self.align = LabelAlign()    
        self.seconds_only = NBool()    
        self.special = LabelSpecial()    

        #Property IDs:
        self._item_id = 80
        self._time_counter = 466
        self._align = 391
        self._seconds_only = 389
        self._special = 390


class UITrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.group_id = NInt()    #Actual type is GroupID()
        self.ui_target = NInt()    #Actual type is GroupID()
        self.xref_pos = UIRef()    
        self.yref_pos = UIRef()    
        self.xref_relative = NBool()    
        self.yref_relative = NBool()    

        #Property IDs:
        self._group_id = 51
        self._ui_target = 71
        self._xref_pos = 385
        self._yref_pos = 386
        self._xref_relative = 387
        self._yref_relative = 388


class CollisionTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.block_a_id = NInt()    #Actual type is BlockID()
        self.block_b_id = NInt()    #Actual type is BlockID()
        self.target_id = NInt()    #Actual type is GroupID()
        self.activate_group = NBool()    
        self.trigger_on_exit = NBool()    
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.pp = NBool()    

        #Property IDs:
        self._block_a_id = 80
        self._block_b_id = 95
        self._target_id = 51
        self._activate_group = 56
        self._trigger_on_exit = 93
        self._p1 = 138
        self._p2 = 200
        self._pp = 201


class InstantCollisionTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.block_a_id = NInt()    #Actual type is BlockID()
        self.block_b_id = NInt()    #Actual type is BlockID()
        self.true_id = NInt()    #Actual type is GroupID()
        self.false_id = NInt()    #Actual type is GroupID()
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.pp = NBool()    

        #Property IDs:
        self._block_a_id = 80
        self._block_b_id = 95
        self._true_id = 51
        self._false_id = 71
        self._p1 = 138
        self._p2 = 200
        self._pp = 201


class CollisionStateBlock(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.state_on = NInt()    #Actual type is GroupID()
        self.state_off = NInt()    #Actual type is GroupID()

        #Property IDs:
        self._state_on = 51
        self._state_off = 71


class CollisionBlock(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.block_id = NInt()    #Actual type is BlockID()
        self.dynamic_block = NBool()    

        #Property IDs:
        self._block_id = 80
        self._dynamic_block = 94


class ToggleBlock(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.group_id = NInt()    #Actual type is GroupID()
        self.activate_group = NBool()    
        self.claim_touch = NBool()    
        self.spawn_only = NBool()    

        #Property IDs:
        self._group_id = 51
        self._activate_group = 56
        self._claim_touch = 445
        self._spawn_only = 504


class OptionsTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.streak_additive = OptionSet()    
        self.hide_ground = OptionSet()    
        self.hide_mg = OptionSet()    
        self.hide_p1 = OptionSet()    
        self.hide_p2 = OptionSet()    
        self.disable_p1_controls = OptionSet()    
        self.disable_p2_controls = OptionSet()    
        self.unlink_dual_gravity = OptionSet()    
        self.hide_attempts = OptionSet()    
        self.audio_on_death = OptionSet()    
        self.no_death_sfx = OptionSet()    
        self.edit_respawn_time = OptionSet()    
        self.boost_slide = OptionSet()    
        self.respawn_time = NFloat()    

        #Property IDs:
        self._streak_additive = 159
        self._hide_ground = 161
        self._hide_mg = 195
        self._hide_p1 = 162
        self._hide_p2 = 163
        self._disable_p1_controls = 165
        self._disable_p2_controls = 199
        self._unlink_dual_gravity = 160
        self._hide_attempts = 532
        self._audio_on_death = 575
        self._no_death_sfx = 576
        self._edit_respawn_time = 573
        self._boost_slide = 593
        self._respawn_time = 574


class OnDeathTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.group_id = NInt()    #Actual type is GroupID()
        self.activate_group = NBool()    

        #Property IDs:
        self._group_id = 51
        self._activate_group = 56


class GravityTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.gravity = NFloat()    
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.pt = NBool()    

        #Property IDs:
        self._gravity = 148
        self._p1 = 138
        self._p2 = 200
        self._pt = 201


class PlayerControlTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.stop_jump = NBool()    
        self.stop_move = NBool()    
        self.stop_rot = NBool()    
        self.stop_slide = NBool()    

        #Property IDs:
        self._p1 = 138
        self._p2 = 200
        self._stop_jump = 540
        self._stop_move = 541
        self._stop_rot = 542
        self._stop_slide = 543


class TeleportCommon:
    def __init__(self):
        #Property Types:
        self.target_group_id = NInt()    #Actual type is GroupID()
        self.smooth_ease = NBool()    
        self.static_force = NBool()    
        self.static_force_additive = NBool()    
        self.redirect_force = NBool()    
        self.redirect_force_min = NFloat()    
        self.redirect_force_max = NFloat()    
        self.redirect_force_mod = NFloat()    
        self.static_force_value = NFloat()    
        self.save_offset = NBool()    
        self.ignore_x = NBool()    
        self.ignore_y = NBool()    
        self.exit_gravity = TeleportGravity()    
        self.instant_camera = NBool()    
        self.snap_ground = NBool()    
        self.redirect_dash = NBool()    

        #Property IDs:
        self._target_group_id = 51
        self._smooth_ease = 55
        self._static_force = 345
        self._static_force_additive = 443
        self._redirect_force = 347
        self._redirect_force_min = 348
        self._redirect_force_max = 349
        self._redirect_force_mod = 350
        self._static_force_value = 346
        self._save_offset = 351
        self._ignore_x = 352
        self._ignore_y = 353
        self._exit_gravity = 354
        self._instant_camera = 464
        self._snap_ground = 510
        self._redirect_dash = 591


class TeleportTrigger(TeleportCommon, Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class BlueTeleportal(TeleportCommon, Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class TeleportOrb(TeleportCommon, Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        pass

        #Property IDs:



class ShaderTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.disable_all = NBool()    
        self.no_player_particles = NBool()    
        self.lowest_layer = TriggerLayer()    
        self.highest_layer = TriggerLayer()    

        #Property IDs:
        self._disable_all = 192
        self._no_player_particles = 188
        self._lowest_layer = 196
        self._highest_layer = 197


class ShaderTriggerCommon(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.relative = NBool()    
        self.animate = NBool()    
        self.shader_disable = NBool()    

        #Property IDs:
        self._relative = 514
        self._animate = 513
        self._shader_disable = 531


class ShockwaveShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.speed = NFloat()    
        self.strength = NFloat()    
        self.thickness = NFloat()    
        self.wave_w = NFloat()    
        self.fade_in = NFloat()    
        self.fade_out = NFloat()    
        self.time_off = NFloat()    
        self.max_size = NFloat()    
        self.screen_offx = NFloat()    
        self.screen_offy = NFloat()    
        self.invert = NBool()    
        self.inner = NFloat()    
        self.outer = NFloat()    
        self.target = NBool()    
        self.center_id = NInt()    #Actual type is GroupID()
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.follow = NBool()    

        #Property IDs:
        self._speed = 175
        self._strength = 176
        self._thickness = 180
        self._wave_w = 179
        self._fade_in = 181
        self._fade_out = 182
        self._time_off = 177
        self._max_size = 512
        self._screen_offx = 290
        self._screen_offy = 291
        self._invert = 184
        self._inner = 183
        self._outer = 191
        self._target = 188
        self._center_id = 51
        self._p1 = 138
        self._p2 = 200
        self._follow = 190


class ShockLineShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.speed = NFloat()    
        self.strength = NFloat()    
        self.thickness = NFloat()    
        self.wave_w = NFloat()    
        self.fade_in = NFloat()    
        self.fade_out = NFloat()    
        self.time_off = NFloat()    
        self.max_size = NFloat()    
        self.screen_off = NFloat()    
        self.invert = NBool()    
        self.flip = NBool()    
        self.rotate = NBool()    
        self.dual = NBool()    
        self.target = NBool()    
        self.center_id = NInt()    #Actual type is GroupID()
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.follow = NBool()    

        #Property IDs:
        self._speed = 175
        self._strength = 176
        self._thickness = 180
        self._wave_w = 179
        self._fade_in = 181
        self._fade_out = 182
        self._time_off = 177
        self._max_size = 512
        self._screen_off = 290
        self._invert = 184
        self._flip = 185
        self._rotate = 186
        self._dual = 187
        self._target = 188
        self._center_id = 51
        self._p1 = 138
        self._p2 = 200
        self._follow = 190


class GlitchShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.strength = NFloat()    
        self.speed = NFloat()    
        self.slice_height = NFloat()    
        self.max_slice_x_off = NFloat()    
        self.max_col_x_off = NFloat()    
        self.max_col_y_off = NFloat()    

        #Property IDs:
        self._strength = 176
        self._speed = 175
        self._slice_height = 179
        self._max_slice_x_off = 191
        self._max_col_x_off = 181
        self._max_col_y_off = 182


class ChromaticShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_x = NFloat()    
        self.target_y = NFloat()    
        self.use_x = NBool()    
        self.use_y = NBool()    

        #Property IDs:
        self._target_x = 180
        self._target_y = 189
        self._use_x = 188
        self._use_y = 190


class ChromaGlitchShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.speed = NFloat()    
        self.rgb_off = NFloat()    
        self.strength = NFloat()    
        self.line_thickness = NFloat()    
        self.segment_h = NFloat()    
        self.line_strength = NFloat()    
        self.disable = NBool()    
        self.relative_pos = NBool()    

        #Property IDs:
        self._speed = 175
        self._rgb_off = 180
        self._strength = 176
        self._line_thickness = 179
        self._segment_h = 189
        self._line_strength = 191
        self._disable = 192
        self._relative_pos = 194


class PixelateShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_x = NFloat()    
        self.target_y = NFloat()    
        self.use_x = NBool()    
        self.use_y = NBool()    
        self.snap_grid = NBool()    
        self.hard_edges = NBool()    

        #Property IDs:
        self._target_x = 180
        self._target_y = 189
        self._use_x = 188
        self._use_y = 190
        self._snap_grid = 194
        self._hard_edges = 515


class LensCircleShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.size = NFloat()    
        self.fade = NFloat()    
        self.strength = NFloat()    
        self.screen_offx = NFloat()    
        self.screen_offy = NFloat()    
        self.center_id = NInt()    #Actual type is GroupID()
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.tint_channel = NInt()    #Actual type is ColorID()

        #Property IDs:
        self._size = 179
        self._fade = 181
        self._strength = 176
        self._screen_offx = 290
        self._screen_offy = 291
        self._center_id = 51
        self._p1 = 138
        self._p2 = 200
        self._tint_channel = 71


class RadialBlurShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.size = NFloat()    
        self.intensity = NFloat()    
        self.ref_channel = NInt()    
        self.screen_offx = NFloat()    
        self.screen_offy = NFloat()    
        self.fade = NFloat()    
        self.target = NBool()    
        self.center_id = NInt()    #Actual type is GroupID()
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.empty_only = NBool()    

        #Property IDs:
        self._size = 179
        self._intensity = 176
        self._ref_channel = 71
        self._screen_offx = 290
        self._screen_offy = 291
        self._fade = 181
        self._target = 188
        self._center_id = 51
        self._p1 = 138
        self._p2 = 200
        self._empty_only = 515


class MotionBlurShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_x = NFloat()    
        self.target_y = NFloat()    
        self.ref_channel = NInt()    
        self.fade = NFloat()    
        self.intensity = NFloat()    
        self.follow_ease = NFloat()    
        self.use_x = NBool()    
        self.use_y = NBool()    
        self.empty_only = NBool()    
        self.dual_dir = NBool()    
        self.target_id = NInt()    #Actual type is GroupID()
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.c = NBool()    

        #Property IDs:
        self._target_x = 180
        self._target_y = 189
        self._ref_channel = 71
        self._fade = 181
        self._intensity = 176
        self._follow_ease = 191
        self._use_x = 188
        self._use_y = 190
        self._empty_only = 515
        self._dual_dir = 194
        self._target_id = 51
        self._p1 = 138
        self._p2 = 200
        self._c = 201


class BulgeShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.bulge = NFloat()    
        self.radius = NFloat()    
        self.screen_offx = NFloat()    
        self.screen_offy = NFloat()    
        self.target = NBool()    
        self.center_id = NInt()    #Actual type is GroupID()
        self.p1 = NBool()    
        self.p2 = NBool()    

        #Property IDs:
        self._bulge = 176
        self._radius = 180
        self._screen_offx = 290
        self._screen_offy = 291
        self._target = 188
        self._center_id = 51
        self._p1 = 138
        self._p2 = 200


class PinchShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target_x = NFloat()    
        self.target_y = NFloat()    
        self.screen_off_x = NFloat()    
        self.screen_off_y = NFloat()    
        self.radius = NFloat()    
        self.modifier = NFloat()    
        self.use_x = NBool()    
        self.use_y = NBool()    

        #Property IDs:
        self._target_x = 180
        self._target_y = 189
        self._screen_off_x = 290
        self._screen_off_y = 291
        self._radius = 512
        self._modifier = 179
        self._use_x = 190
        self._use_y = 194


class GrayscaleShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target = NFloat()    
        self.tint_channel = NInt()    #Actual type is ColorID()
        self.tint_channel_checkbox = NBool()    
        self.use_lum = NBool()    

        #Property IDs:
        self._target = 176
        self._tint_channel = 51
        self._tint_channel_checkbox = 190
        self._use_lum = 188


class SepiaShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target = NFloat()    

        #Property IDs:
        self._target = 176


class InvertColorShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.target = NFloat()    
        self.r = NFloat()    
        self.g = NFloat()    
        self.b = NFloat()    
        self.edit_rgb = NBool()    
        self.tween_rgb = NBool()    
        self.clamp_rgb = NBool()    

        #Property IDs:
        self._target = 176
        self._r = 179
        self._g = 180
        self._b = 189
        self._edit_rgb = 188
        self._tween_rgb = 190
        self._clamp_rgb = 194


class HueShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.degrees = NFloat()    

        #Property IDs:
        self._degrees = 176


class EditColorShaderTrigger(ShaderTriggerCommon):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.cr = NFloat()    
        self.cg = NFloat()    
        self.cb = NFloat()    
        self.br = NFloat()    
        self.bg = NFloat()    
        self.bb = NFloat()    

        #Property IDs:
        self._cr = 176
        self._cg = 191
        self._cb = 175
        self._br = 179
        self._bg = 180
        self._bb = 189


class EnterEffectTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.enter_exit_only = EnterExitOnly()    
        self.target_enter_channel = NInt()    

        #Property IDs:
        self._enter_exit_only = 217
        self._target_enter_channel = 344


class EditSongTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.song_channel = NInt()    
        self.stop = NBool()    
        self.stop_loop = NBool()    
        self.speed = NInt()    
        self.change_speed = NBool()    
        self.volume = NFloat()    
        self.change_volume = NBool()    
        self.group_id_1 = NInt()    #Actual type is GroupID()
        self.group_id_2 = NInt()    #Actual type is GroupID()
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.cam = NBool()    
        self.vol_near = NFloat()    
        self.vol_med = NFloat()    
        self.vol_far = NFloat()    
        self.min_dist = NInt()    
        self.dist_2 = NInt()    
        self.dist_3 = NInt()    
        self.dir_buttons = SoundDirs()    

        #Property IDs:
        self._song_channel = 432
        self._stop = 417
        self._stop_loop = 414
        self._speed = 404
        self._change_speed = 419
        self._volume = 406
        self._change_volume = 418
        self._group_id_1 = 51
        self._group_id_2 = 71
        self._p1 = 138
        self._p2 = 200
        self._cam = 428
        self._vol_near = 421
        self._vol_med = 422
        self._vol_far = 423
        self._min_dist = 424
        self._dist_2 = 425
        self._dist_3 = 426
        self._dir_buttons = 458


class EditSFXTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.group_id = NInt()    #Actual type is GroupID()
        self.sfx_group = NInt()    #Actual type is SFXGroup()
        self.unique_id = NInt()    #Actual type is UniqueID()
        self.stop = NBool()    
        self.stop_loop = NBool()    
        self.speed = NInt()    
        self.change_speed = NBool()    
        self.volume = NFloat()    
        self.change_volume = NBool()    
        self.group_id_1 = NInt()    #Actual type is GroupID()
        self.group_id_2 = NInt()    #Actual type is GroupID()
        self.p1 = NBool()    
        self.p2 = NBool()    
        self.cam = NBool()    
        self.vol_near = NFloat()    
        self.vol_med = NFloat()    
        self.vol_far = NFloat()    
        self.min_dist = NInt()    
        self.dist_2 = NInt()    
        self.dist_3 = NInt()    
        self.dir_buttons = SoundDirs()    

        #Property IDs:
        self._group_id = 457
        self._sfx_group = 455
        self._unique_id = 416
        self._stop = 417
        self._stop_loop = 414
        self._speed = 404
        self._change_speed = 419
        self._volume = 406
        self._change_volume = 418
        self._group_id_1 = 51
        self._group_id_2 = 71
        self._p1 = 138
        self._p2 = 200
        self._cam = 428
        self._vol_near = 421
        self._vol_med = 422
        self._vol_far = 423
        self._min_dist = 424
        self._dist_2 = 425
        self._dist_3 = 426
        self._dir_buttons = 458


class ForceBlock(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.relative = NBool()    
        self.force = NFloat()    
        self.min_force = NFloat()    
        self.max_force = NFloat()    
        self.range = NBool()    
        self.force_id = NInt()    #Actual type is ForceID()

        #Property IDs:
        self._relative = 528
        self._force = 149
        self._min_force = 526
        self._max_force = 527
        self._range = 529
        self._force_id = 530


class EndTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.spawn_id = NInt()    #Actual type is GroupID()
        self.target_pos = NInt()    #Actual type is GroupID()
        self.no_end_effects = NBool()    
        self.instant = NBool()    
        self.no_sfx = NBool()    

        #Property IDs:
        self._spawn_id = 51
        self._target_pos = 71
        self._no_end_effects = 460
        self._instant = 487
        self._no_sfx = 461


class SecretCoin(AnimatedObject):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.coin_id = NInt()    

        #Property IDs:
        self._coin_id = 12


class OldEndTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.group_id = NInt()    #Actual type is GroupID()
        self.lock_y = NBool()    
        self.reversed = NBool()    

        #Property IDs:
        self._group_id = 51
        self._lock_y = 59
        self._reversed = 118


class Template(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.reference_only = NBool()    

        #Property IDs:
        self._reference_only = 157


class CheckpointTrigger(Trigger):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.respawn_id = NInt()    #Actual type is GroupID()

        #Property IDs:
        self._respawn_id = 448


class BPMGuide(Common):
    def __init__(self):
        super().__init__()

        #Property Types:
        self.bpm = NInt()    
        self.speed = BPMSpeed()    
        self.disable = NBool()    
        self.bpb = NInt()    

        #Property IDs:
        self._bpm = 498
        self._speed = 499
        self._disable = 500
        self._bpb = 501


